### ISSUE TITLE
Unable to boot into TWRP (NO ROOT)

### ISSUE THREAD

**Issue by Hanakohiraki** [TheNoobDevs/custom_twrp_samsung_a05s#2]
doesn't bootloop. Here are the steps on my device.

 After installing TWRP using odin

 Power button + Volume down button until it turns off.

 ↓

 Don't release the power button + volume up button + release the volume down button.

 ↓

 Samsung logo (power button + volume up button not yet released)

 ↓

 OEM warning disconnected (don't press power button to skip)

 ↓

 Samsung galaxy logo with not Samsung software (still press the volume button But release the power button)

 ↓

 My phone vibrates

 Then enter android normally.

 When I use ADB to Recovery it turns out to be Android Recovery??? TWRP is uninstalled itself???

**Comment by TheNoobDevs** [comment]
Some devices restore android default recovery after reboot, this tree needs work still, then the Samsung logo comes up and the device reboots, do you see writing on the top left of the screen?

**Comment by Hanakohiraki** [comment]
What do you mean? Do you have a Telagram?
